**PROGRAM 1**
 Basic array creation

In [ ]:
import numpy as np
array_from_list = np.array([1, 2, 3, 4, 5])
print("Array from list:", array_from_list)
array_with_range = np.arange(10)
print("Array with range:", array_with_range)
zeros_array = np.zeros((3, 3))
print("Array of zeros:\n", zeros_array)
ones_array = np.ones((2, 5))
print("Array of ones: In", ones_array)

Array from list: [1 2 3 4 5]
Array with range: [0 1 2 3 4 5 6 7 8 9]
Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array of ones: In [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


2.Array Operations

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

add_result = np.add(a, b)
print("Addition:", add_result)

sub_result = np.subtract(a, b)
print("Subtraction:", sub_result)

mul_result = np.multiply(a, b)
print("Multiplication:", mul_result)


div_result = np.divide(a, b)
print("Division:", div_result)


Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


3.Array Reshapping

In [ ]:
import numpy as np
array = np.arange (12)
print("Original array:", array)
reshaped_array = array.reshape((3,4))
print("Reshaped to 3x4:\n", reshaped_array)
reshaped_array_3d = array.reshape((2, 3, 2))
print("Reshaped to 2x3x2:\n", reshaped_array_3d)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped to 2x3x2:
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


4.Indexing and Slicing

In [ ]:
import numpy as np
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array: \n", array_2d)
element = array_2d[1, 2]
print("Element at (1, 2):", element)

2D Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at (1, 2): 6


**PROGRAM 2**
Create two 2D arrays using array object and
a. Add the 2 matrices and print it
b. Subtract 2 matrices
c. Multiply the individual elements of matrix
d. Divide the elements of the matrices
e. Perform matrix multiplication
f. Display transpose of the matrix
g. Sum of diagonal elements of a matrix

In [ ]:
import numpy as np
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

matrix_sum = matrix1 + matrix2
matrix_diff = matrix1 - matrix2
matrix_product = matrix1 * matrix2
matrix_divide = matrix1 / matrix2
matrix_multiply = np.dot(matrix1, matrix2)
matrix1_transpose = np.transpose(matrix1)
diagonal_sum = np.trace(matrix1)

print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Matrix Sum:\n", matrix_sum)
print("Matrix Difference:\n", matrix_diff)
print("Matrix Element-wise Product:\n", matrix_product)
print("Matrix Element-wise Division:\n", matrix_divide)
print("Matrix Multiplication:\n", matrix_multiply)
print("Transpose of Matrix 1:\n", matrix1_transpose)
print("Sum of Diagonal Elements of Matrix 1:", diagonal_sum)


subarray = array_2d[1:3, 0:2]
print("Sliced subarray:\n", subarray)

column = array_2d[:, 1]
print("Column 1 of array_2d:", column)


Matrix 1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix 2:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Matrix Sum:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Matrix Difference:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
Matrix Element-wise Product:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Matrix Element-wise Division:
 [[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]
Matrix Multiplication:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Transpose of Matrix 1:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Sum of Diagonal Elements of Matrix 1: 15
Sliced subarray:
 [[4 5]
 [7 8]]
Column 1 of array_2d: [2 5 8]


STATISTICAL OPERATIONS

In [9]:
import numpy as np
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

mean = np.mean(array)
print("Mean:", mean)
median = np.median(array)
print("Median:", median)
std_dev = np.std(array)
print("Standard Deviation:", std_dev)
min_val = np.min(array)
max_val = np.max(array)
print("Minimum value:", min_val)
print("Maximum value:", max_val)


Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Minimum value: 1
Maximum value: 10


PROGRAM 3
Write a program to display the elements of the matrix X to different powers and identity matrix of a given matrix Also create another matrix Y with same dimensions and display X2 +2Y


In [8]:
import numpy as np

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
print("Matrix X is:\n", x)
print("Matrix Y is:\n", y)
a = np.power(x, 2)
print("X ^2=",a)
result =a+2*y
print("X^2+2Y=",result)


Matrix X is:
 [[1 2]
 [3 4]]
Matrix Y is:
 [[5 6]
 [7 8]]
X ^2= [[ 1  4]
 [ 9 16]]
X^2+2Y= [[11 16]
 [23 32]]
